### ISSUE TITLE
fragment初始化失败

### ISSUE THREAD

**Issue by chenyue404** [Cricin/Folivora#4]
版本0.0.7
使用方式：wrap和installViewFactory都不行
重现方式：
acitivty里面放viewpager，viewpager里面放fragment

**Comment by Cricin** [comment]
可以贴一下奔溃的log吗

**Comment by chenyue404** [comment]
日志如下。  
```
2019-04-24 09:17:56.035 5212-5212/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.*, PID: 5212
    android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at cn.cricin.folivora.FolivoraViewFactory.onCreateView(FolivoraViewFactory.java:86)
        at cn.cricin.folivora.FolivoraViewFactory.onCreateView(FolivoraViewFactory.java:58)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:193)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:496)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.*.me.MeFragment.createView(MeFragment.java:38)
        at com.*.base.BaseFragment.onCreateView(BaseFragment.java:25)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:168)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1244)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
2019-04-24 09:17:56.036 5212-5212/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:849)
        at android.view.View.measure(View.java:21051)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2587)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1646)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1897)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1526)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7102)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:638)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:392)
        at android.view.View.<init>(View.java:4317)
        at android.view.View.<init>(View.java:4460)
        at android.view.ViewGroup.<init>(ViewGroup.java:579)
        at android.widget.FrameLayout.<init>(FrameLayout.java:92)
        at android.widget.FrameLayout.<init>(FrameLayout.java:87)
        at android.widget.FrameLayout.<init>(FrameLayout.java:82)
        	... 69 more
```

**Comment by Cricin** [comment]
没法重现这个异常，我在ViewPager里放了Fragment，inflate的时候不会报错。这个异常是偶发的吗？能不能写个有问题的demo给我呢

**Comment by chenyue404** [comment]
https://github.com/chenyue404/FolivoraTest

**Comment by chenyue404** [comment]
奇怪，家里电脑跑出来就没问题，公司电脑就不行。

**Comment by Cricin** [comment]
我这边跑你给的demo也是没有问题的，我觉得这个问题应该和Android版本有关。

**Comment by chenyue404** [comment]
试了下，应该就是Android版本问题了，我试了6.0，7.0，7.1的都不行，8.0以上的可以。

**Comment by Cricin** [comment]
刚看了下不同版本的LayoutInflater#createView()的源码，的确是有不同，下个版本我会试着修复这个问题

**Comment by Cricin** [comment]
0.0.8版本修复了，你可以试一下

**Comment by chenyue404** [comment]
可以了，给力。
